### ISSUE TITLE
nr1 nerdpack:serve error on build

### ISSUE THREAD

**Issue by rflores-pplsi** [newrelic/newrelic-cli#1566]
### Description
new install from installer of CLI

### Go Version
N/A

### Current behavior
Following the "get started" guide, I am unable to build my first nerdpack/nerdlet

### Expected behavior
local server is able to show "Hello World" app

### Steps To Reproduce
1. [ following the initial setup guide](https://onenr.io/0Bj3XxL42QX)
2. nr1 create - enter, enter, enter
3. cd dysfunctional-spoon ( auto-generated name ) 
4. npm start

### Debug Output (if applicable)
```
dysfunctional-spoon npm start

> dysfunctional-spoon@0.1.0 start
> nr1 nerdpack:serve

Found and loaded 2 nr1.json files on DysfunctionalSpoon (c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8) Nerdpack.

Nerdpack:
 ✔  DysfunctionalSpoon (c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8) nr1.json

Launchers:
 ✔  launcher launchers/launcher/nr1.json

Nerdlets:
 ✔  home nerdlets/home/nr1.json

Webpack bundle analyzer is enabled (you need to wait for the first build to finish)
 └  You can head to http://127.0.0.1:27888

NOTE: To verify how your assets will look in production, you need to
      add "--mode=prod" when starting the development server.

🛠  Built artifact files for:ex.js...
 ⁎  c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home built ✔
Hash: 8d64c340435b9ee9687834976ab2bdb35ce1e079
Version: webpack 4.46.0
Child
    Hash: 8d64c340435b9ee96878
    Time: 1339ms
    Built at: 03/06/2024 11:27:31 AM
                                                   Asset      Size                                      Chunks             Chunk Names
    c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home~latest.js  25.8 KiB  c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home  [emitted]  c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home
    Entrypoint c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home = c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home~latest.js
    [../../../../usr/local/lib/newrelic-cli/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js] /usr/local/lib/newrelic-cli/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js 259 bytes {c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home} [built]
    [../../../../usr/local/lib/newrelic-cli/node_modules/@babel/runtime/helpers/esm/setPrototypeOf.js] /usr/local/lib/newrelic-cli/node_modules/@babel/runtime/helpers/esm/setPrototypeOf.js 229 bytes {c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home} [built]
    [./nerdlets/home/index.js] 976 bytes {c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home} [built]
    [__nr1-internal__] external "(function() { throw new Error(\"Could not initialize \\\"__nr1-internal__\\\"\"); })()" 42 bytes {c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--home} [built]
Child
    Hash: 34976ab2bdb35ce1e079
    Time: 30ms
    Built at: 03/06/2024 11:27:31 AM
                                              Asset      Size                                        Chunks  Chunk Names
    c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles.js  10.9 KiB  c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles  c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles
    Entrypoint c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles = c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles.js
    [./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss] 2.05 KiB {c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8--styles} [built] [failed] [1 error]
    
    ERROR in ./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss
    Module build failed (from /usr/local/lib/newrelic-cli/node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleError: Module Error (from /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js):
    Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'
    Require stack:
    - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/utils.js
    - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/index.js
    - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js
    - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/loadLoader.js
    - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js
    - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js
    - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModuleFactory.js
    - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/Compiler.js
    - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/webpack.js
    - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack/src/build/BuildManager.js
    - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack-serve/src/commands/nerdpack/serve.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/module-loader.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/plugin.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/config.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/index.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/command.js
    - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/index.js
    - /usr/local/lib/newrelic-cli/bin/run
    
    (@/Users/floresrb/Desktop/dysfunctional-spoon/tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss)
        at Object.emitError (/usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js:173:6)
        at getPostcssOptions (/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/utils.js:196:19)
        at Object.loader (/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/index.js:65:36)
    Child mini-css-extract-plugin ../../../../usr/local/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!../../../../usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js??ref--5-2!../../../../usr/local/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js!tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss:
        Entrypoint mini-css-extract-plugin = *
        [../../../../usr/local/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js?!../../../../usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js?!../../../../usr/local/lib/newrelic-cli/node_modules/fast-sass-loader/lib/index.js!./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss] /usr/local/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js??ref--5-2!/usr/local/lib/newrelic-cli/node_modules/fast-sass-loader/lib!./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss 790 bytes {mini-css-extract-plugin} [built] [1 error]
        [../../../../usr/local/lib/newrelic-cli/node_modules/css-loader/dist/runtime/api.js] /usr/local/lib/newrelic-cli/node_modules/css-loader/dist/runtime/api.js 1.57 KiB {mini-css-extract-plugin}
        [../../../../usr/local/lib/newrelic-cli/node_modules/css-loader/dist/runtime/cssWithMappingToString.js] /usr/local/lib/newrelic-cli/node_modules/css-loader/dist/runtime/cssWithMappingToString.js 2.27 KiB {mini-css-extract-plugin}
        
        ERROR in ./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss (/usr/local/lib/newrelic-cli/node_modules/css-loader/dist/cjs.js??ref--5-1!/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js??ref--5-2!/usr/local/lib/newrelic-cli/node_modules/fast-sass-loader/lib!./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss)
        Module Error (from /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js):
        Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'
        Require stack:
        - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/utils.js
        - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/index.js
        - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js
        - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/loadLoader.js
        - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js
        - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js
        - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModuleFactory.js
        - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/Compiler.js
        - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/webpack.js
        - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack/src/build/BuildManager.js
        - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack-serve/src/commands/nerdpack/serve.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/module-loader.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/plugin.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/config.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/index.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/command.js
        - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/index.js
        - /usr/local/lib/newrelic-cli/bin/run
        
        (@/Users/floresrb/Desktop/dysfunctional-spoon/tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss)

 ›   Error: (undefined) ./tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss
 ›   Module build failed (from /usr/local/lib/newrelic-cli/node_modules/mini-css-extract-plugin/dist/loader.js):
 ›   ModuleError: Module Error (from /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js):
 ›   Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'
 ›   Require stack:
 ›   - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/utils.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/index.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/cjs.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/loadLoader.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/loader-runner/lib/LoaderRunner.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModuleFactory.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/Compiler.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/webpack/lib/webpack.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack/src/build/BuildManager.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-nerdpack-serve/src/commands/nerdpack/serve.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/module-loader.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/plugin.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/config.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/config/index.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/command.js
 ›   - /usr/local/lib/newrelic-cli/node_modules/@oclif/core/lib/index.js
 ›   - /usr/local/lib/newrelic-cli/bin/run
 ›
 ›   (@/Users/floresrb/Desktop/dysfunctional-spoon/tmp/c1d1dcce-a1bb-4f1c-b466-ec1e7aa945d8-styles.1709742450091.scss)
 ›       at Object.emitError (/usr/local/lib/newrelic-cli/node_modules/webpack/lib/NormalModule.js:173:6)
 ›       at getPostcssOptions (/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/utils.js:196:19)
 ›       at Object.loader (/usr/local/lib/newrelic-cli/node_modules/postcss-loader/dist/index.js:65:36)
 ›   Code: UNKNOWN

```

### Additional Context
- @datanerd/nr1/2.83.5 darwin-x64 node-v16.11.1
- node -v: 19.0.0
- 
### References or Related Issues
I was not able to find any related issues

**Comment by sanderblue** [comment]
Hi @rflores-pplsi, the `nr1` CLI is a different CLI than this one, but you could try running `nr1 update` and `npm install` and retry. But if that doesn't work, for help with the `nr1` CLI, you can reach out to [support](https://support.newrelic.com/s/) or try our [Explorers Hub](https://forum.newrelic.com/s/).
